version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) 
      - dockerd
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t trade .
      - docker tag trade:latest 112314172997.dkr.ecr.ap-south-1.amazonaws.com/fire:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 112314172997.dkr.ecr.ap-south-1.amazonaws.com/fire:latest
      - echo Writing image definitions file...
      - printf '[{"name":"fire","imageUri":"%s"}]' 112314172997.dkr.ecr.ap-south-1.amazonaws.com/fire:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
