version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t test .
      - docker tag test:latest 668853609085.dkr.ecr.ap-south-1.amazonaws.com/image:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 668853609085.dkr.ecr.ap-south-1.amazonaws.com/image:latest
      - echo Writing image definitions file...
      - printf '[{"name":"test","imageUri":"%s"}]' 668853609085.dkr.ecr.ap-south-1.amazonaws.com/image:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
