version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) 
      - dockerd
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t fire .
      - docker tag fire:latest 645369028999.dkr.ecr.us-east-1.amazonaws.com/fire:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 645369028999.dkr.ecr.us-east-1.amazonaws.com/fire:latest
      - echo Writing image definitions file...
      - printf '[{"name":"fire","imageUri":"%s"}]' 645369028999.dkr.ecr.us-east-1.amazonaws.com/fire:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
